# Generated by Django 5.2.7 on 2025-12-04 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissaoEspacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('agencia', models.CharField(max_length=100)),
                ('data_lancamento', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('objetivo', models.TextField()),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('ativa', 'Ativa'), ('concluida', 'Concluída'), ('falhou', 'Falhou'), ('cancelada', 'Cancelada')], max_length=20)),
                ('tipo', models.CharField(choices=[('orbital', 'Orbital'), ('lunar', 'Lunar'), ('planetaria', 'Planetária'), ('solar', 'Sistema Solar'), ('interestelar', 'Interestelar'), ('observacao', 'Observação'), ('comunicacao', 'Comunicação'), ('ciencia', 'Ciência')], default='orbital', max_length=20)),
                ('orcamento', models.DecimalField(blank=True, decimal_places=2, help_text='Orçamento em milhões de dólares', max_digits=15, null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='missoes/')),
                ('curiosidades', models.TextField()),
            ],
            options={
                'verbose_name': 'Missão Espacial',
                'verbose_name_plural': 'Missões Espaciais',
                'ordering': ['-data_lancamento'],
            },
        ),
        migrations.CreateModel(
            name='Astronauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('data_falecimento', models.DateField(blank=True, null=True)),
                ('genero', models.CharField(choices=[('M', 'Masculino'), ('F', 'Feminino'), ('O', 'Outro')], default='M', max_length=1)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('aposentado', 'Aposentado'), ('falecido', 'Falecido')], default='ativo', max_length=20)),
                ('foto', models.ImageField(blank=True, null=True, upload_to='astronautas/')),
                ('biografia', models.TextField()),
                ('missoes', models.ManyToManyField(blank=True, related_name='tripulantes', to='exploracao_espacial.missaoespacial')),
            ],
            options={
                'verbose_name': 'Astronauta',
                'verbose_name_plural': 'Astronautas',
                'ordering': ['nome'],
            },
        ),
    ]
