# Generated by Django 5.2.7 on 2025-11-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MissaoEspacial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('agencia', models.CharField(max_length=100)),
                ('data_lancamento', models.DateField()),
                ('data_termino', models.DateField(blank=True, null=True)),
                ('objetivo', models.TextField()),
                ('status', models.CharField(choices=[('planejada', 'Planejada'), ('ativa', 'Ativa'), ('concluida', 'Concluída'), ('falhou', 'Falhou')], max_length=20)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='missoes/')),
                ('curiosidades', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Astronauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, unique=True)),
                ('nacionalidade', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('foto', models.ImageField(blank=True, null=True, upload_to='astronautas/')),
                ('biografia', models.TextField()),
                ('missoes', models.ManyToManyField(blank=True, to='exploracao_espacial.missaoespacial')),
            ],
        ),
    ]
