# Generated by Django 5.2.7 on 2025-11-05 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('ana_amarela', 'Anã Amarela'), ('ana_vermelha', 'Anã Vermelha'), ('gigante_vermelha', 'Gigante Vermelha'), ('gigante_azul', 'Gigante Azul')], max_length=50)),
                ('massa', models.FloatField(help_text='1.0 = massa do Sol (1.989 × 10³⁰ kg)')),
                ('temperatura', models.IntegerField(blank=True, help_text='Em Kelvin. Ex: Sol = 5778 K', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='estrelas/')),
                ('sistema_planetario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.sistemaplanetario')),
            ],
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('rochoso', 'Rochoso'), ('gasoso', 'Gasoso'), ('gelado', 'Gelado'), ('anao', 'Anão')], max_length=20)),
                ('diametro', models.FloatField(help_text='Em km')),
                ('temperatura_media', models.IntegerField(blank=True, help_text='Temperatura em Kelvin', null=True)),
                ('possui_agua', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='planetas/')),
                ('curiosidades', models.TextField()),
                ('sistema_planetario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.sistemaplanetario')),
            ],
        ),
        migrations.CreateModel(
            name='SateliteNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('diametro', models.FloatField(help_text='Em km')),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='satelites/')),
                ('planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='corpos_celestes.planeta')),
            ],
        ),
    ]
