# Generated by Django 5.2.7 on 2025-12-04 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('universo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estrela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('classificacao_espectral', models.CharField(blank=True, choices=[('O', 'Azul muito quente'), ('B', 'Azul'), ('A', 'Branco-azulada'), ('F', 'Branca'), ('G', 'Amarela'), ('K', 'Laranja'), ('M', 'Vermelha')], max_length=1, null=True)),
                ('estagio_evolutivo', models.CharField(choices=[('protoestrela', 'Protoestrela'), ('sequencia_principal', 'Sequência Principal'), ('ana_vermelha', 'Anã Vermelha'), ('ana_laranja', 'Anã Laranja'), ('ana_amarela', 'Anã Amarela'), ('ana_branca', 'Anã Branca'), ('gigante_vermelha', 'Gigante Vermelha'), ('gigante_azul', 'Gigante Azul'), ('supergigante_vermelha', 'Supergigante Vermelha'), ('supergigante_azul', 'Supergigante Azul'), ('hipergigante', 'Hipergigante'), ('estrela_neutrons', 'Estrela de Nêutrons'), ('pulsar', 'Pulsar'), ('magnetar', 'Magnetar')], max_length=50)),
                ('massa', models.FloatField(help_text='1.0 = massa do Sol (1.989 × 10³⁰ kg)')),
                ('temperatura', models.IntegerField(blank=True, help_text='Em Kelvin (ex: Sol = 5778 K)', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='estrelas/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sistema_planetario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.sistemaplanetario')),
            ],
            options={
                'verbose_name': 'Estrela',
                'verbose_name_plural': 'Estrelas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Planeta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('rochoso', 'Rochoso'), ('gasoso', 'Gasoso'), ('gelado', 'Gelado'), ('anao', 'Anão'), ('superterra', 'Superterra'), ('mininetuno', 'Mini-Netuno')], max_length=20)),
                ('diametro', models.FloatField(help_text='Em km')),
                ('massa', models.FloatField(blank=True, help_text='Massa em massas terrestres (1.0 = Terra)', null=True)),
                ('temperatura_media', models.IntegerField(blank=True, help_text='Temperatura em Kelvin', null=True)),
                ('periodo_orbital', models.FloatField(blank=True, help_text='Período orbital em dias terrestres', null=True)),
                ('possui_agua', models.BooleanField(default=False)),
                ('possui_atmosfera', models.BooleanField(default=False)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='planetas/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('sistema_planetario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='universo.sistemaplanetario')),
            ],
            options={
                'verbose_name': 'Planeta',
                'verbose_name_plural': 'Planetas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SateliteNatural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('diametro', models.FloatField(help_text='Em km')),
                ('massa', models.FloatField(blank=True, help_text='Massa em kg', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='satelites/')),
                ('descricao', models.TextField(blank=True, null=True)),
                ('planeta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='satelites', to='corpos_celestes.planeta')),
            ],
            options={
                'verbose_name': 'Satélite Natural',
                'verbose_name_plural': 'Satélites Naturais',
                'ordering': ['nome'],
            },
        ),
    ]
