# Generated by Django 5.2.7 on 2025-12-04 03:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('espiral', 'Espiral'), ('eliptica', 'Elíptica'), ('irregular', 'Irregular'), ('lenticular', 'Lenticular'), ('anã', 'Galáxia Anã')], max_length=50)),
                ('diametro', models.FloatField(blank=True, help_text='Em anos-luz', null=True)),
                ('massa', models.FloatField(blank=True, help_text='Massa em massas solares', null=True)),
                ('distancia_terra', models.FloatField(blank=True, help_text='Distância da Terra em anos-luz', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galaxias/')),
                ('descricao', models.TextField()),
            ],
            options={
                'verbose_name': 'Galáxia',
                'verbose_name_plural': 'Galáxias',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='Nebulosa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(choices=[('emissao', 'Nebulosa de Emissão'), ('reflexao', 'Nebulosa de Reflexão'), ('negra', 'Nebulosa Escura'), ('planetaria', 'Nebulosa Planetária'), ('supernova', 'Remanescente de Supernova')], max_length=50)),
                ('distancia', models.FloatField(blank=True, help_text='Em anos-luz', null=True)),
                ('diametro', models.FloatField(blank=True, help_text='Diâmetro em anos-luz', null=True)),
                ('magnitude', models.FloatField(blank=True, help_text='Magnitude aparente', null=True)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='nebulosas/')),
            ],
            options={
                'verbose_name': 'Nebulosa',
                'verbose_name_plural': 'Nebulosas',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='SistemaPlanetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('estrela_principal', models.CharField(max_length=100)),
                ('idade', models.FloatField(blank=True, help_text='Em bilhões de anos', null=True)),
                ('numero_planetas', models.IntegerField(blank=True, help_text='Número de planetas confirmados', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sistemas/')),
                ('descricao', models.TextField()),
                ('galaxia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sistemas_planetarios', to='universo.galaxia')),
            ],
            options={
                'verbose_name': 'Sistema Planetário',
                'verbose_name_plural': 'Sistemas Planetários',
                'ordering': ['nome'],
            },
        ),
    ]
