# Generated by Django 5.2.7 on 2025-11-05 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Galaxia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('tipo', models.CharField(max_length=50)),
                ('diametro', models.FloatField(blank=True, help_text='Em anos-luz', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='galaxias/')),
                ('descricao', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SistemaPlanetario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('estrela_principal', models.CharField(max_length=100)),
                ('idade', models.FloatField(blank=True, help_text='Em bilhões de anos', null=True)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='sistemas/')),
                ('descricao', models.TextField()),
                ('galaxia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='universo.galaxia')),
            ],
        ),
    ]
