# Generated by Django 5.2.7 on 2025-11-05 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Destaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('descricao', models.TextField()),
                ('imagem', models.ImageField(upload_to='destaques/')),
                ('link', models.CharField(blank=True, max_length=200)),
                ('ativo', models.BooleanField(default=True)),
                ('data_publicacao', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-data_publicacao'],
            },
        ),
    ]
